public enum UserEventType {
    MENU_PLAY_BUTTON, MENU_SETTINGS, MENU_EXIT, CREATE_NEW_ROOM, CONNECT_TO_EXISTING, BACK_TO_MENU,
    NEW_BARREL, CHECK_NUMBER_IN_TRAY, NUMBER_EXISTS, MISSING_NUMBER, GAME_MENU_OPEN, BACK_TO_GAME,
    APPLY_USER_NAME, APPLY_SERVER_NAME, START_GAME, SHOW_MAIN_MENU, SHOW_ROOM_USERS,
    SEND_MESSAGE, APPEND_INCOMING_MESSAGE, PLAYER_WINS, NOBODY_WINS
}

